### PR TITLE
11081 - Checkbox Component

### PR DESCRIPTION
**Pull request by andreferreiradlw**
[TP11081](https://maps.tpondemand.com/entity/11081-form-checkbox-component)

This PR implements the `Checkbox` component to be used in filtering.

It also improves the `Formfield` component documentation in regards to accessibility usage.

### CODE REVIEW

**Comment by andreferreiradlw** [comment]
@akenzua those are radio buttons are are not on the wireframes from Nakul. They should be addressed on a different ticket anyway

**Comment by akenzua** [comment]
Just citing that, there should be some room. Aesthetically, it should have some breathing space and if we are going to have a radio in the same form, i believe they should align.

**Comment by akenzua** [comment]
The wireframes considered that too:
Nakhuls

**Comment by andreferreiradlw** [comment]
@akenzua that's fine, the `Checkbox` component created here has access to generic props such as `margin` and `padding` that can be set as custom. The current default padding and margin styles come from current rad_consumer

**Comment by akenzua** [comment]
Exactly, i think you should use those, so we wont have to set the margins everywhere we use the checkout box. Since we expect all checkboxes to be uniform. Thats the whole idea of a library, not rewriting the same thing all over, i believe.

**Comment by andreferreiradlw** [comment]
@akenzua the `Checkbox` is already using the styles from rad, there's a `margin` on the input there of `margin-top: 4px;` and `margin-right: 5px;` similar to this. The margins on the wireframe are quite larger but I believe we should follow the existing styles on rad

**Comment by akenzua** [comment]
@andreferreiradlw  i probably did not put my point out correctly, I am not talking about the margins around the checkbox, i am talking the margin between the box itself and its value. @davidtrussler whats your take on this. I really dont have problem letting this go but its what we still have to deal with @ some point.

**Comment by andreferreiradlw** [comment]
It's confusing because the styles in rad are conflicting with the one from the wireframes because of the margin on the input is that right?

**Comment by andreferreiradlw** [comment]
boxes
as you can see they don't look the same

**Comment by davidtrussler** [comment]
I get what @akenzua is saying on this: I can't see any margins applied to the checkbox to be honest so it is using whatever the browser default is. Probably we could make these closer to RAD, which I agree is the one we should be modelling the styles on (i.e. not the wireframes).

**Comment by andreferreiradlw** [comment]
I agree @davidtrussler and that's basically what I've done here.

**Pull request merged**
