### PR TITLE
11587 - Implement core-js

### PR DESCRIPTION
**Pull request by andreferreiradlw**
[TP11587](https://maps.tpondemand.com/entity/11587-implement-corejs-in-library)

After some trial and error testing, finally got a setup that builds the library properly with `Rollup` with support for `core-js` with `Babel`.

Improves `Babel` configuration files to support `core-js` and adds new plugins to apply transformations to the code supporting ES6 syntax. Moves the `browserslist` to be used by `Babel` from the config file to `package.json`.

`styled-components` version bumped to `5.x`. Also updates multiple `Rollup` plugins and improves its build configuration.

Bumps package version to `1.9.0`.

**Note:** Failed to implement [react-app-polyfill](https://www.npmjs.com/package/react-app-polyfill) in the library due to some stubborn errors with Rollup while building the package, this might need revisiting in the future.

**Note 2:** The setup addressed in this PR does not affect the `styleguidist` and `webpack` setup used by the documentation pages.

### CODE REVIEW

**Review by ladamsatmaps19 — APPROVED** [review]
Well done Andre! :)

**Comment by davidtrussler** [comment]
I'm running this on a local server via Ngrok and testing on various browsers on BrowserStack and it is not rendering at all in IE11. It's hard to say whether the problem is in the changes in this PR or in the set up I am using so we may need to deploy this to a test environment to be sure. 

I can't see any problems with the code (although my knowledge of the modules being used here is less than minimal. 😉 )

**Comment by andreferreiradlw** [comment]
> I'm running this on a local server via Ngrok and testing on various browsers on BrowserStack and it is not rendering at all in IE11. It's hard to say whether the problem is in the changes in this PR or in the set up I am using so we may need to deploy this to a test environment to be sure.
> 
> I can't see any problems with the code (although my knowledge of the modules being used here is less than minimal. 😉 )

Yeah these changes won't affect the styleguidist documentation pages, this is only the build with Rollup that will go in the package used by TAD for example so just the output will be affected, not what you run locally. I tried to explain this on note 2 but it can be quite confusing because there are 2 setups in this repo.

**Comment by davidtrussler** [comment]
> Yeah these changes won't affect the styleguidist documentation pages, this is only the build with Rollup that will go in the package used by TAD for example so just the output will be affected, not what you run locally. I tried to explain this on note 2 but it can be quite confusing because there are 2 setups in this repo.
> 
Ah right, got it, it does say that doesn't it. In which case I shall approve the PR. 😄

**Review by davidtrussler — APPROVED** [review]
LGTM! 👍

**Pull request merged**
